name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE: ${{ secrets.HF_SPACE }}
        run: |
          rm -rf .git
          git init -b main
          git lfs install
          git lfs track "*.pkl"
          git lfs track "*.svg"
          git add .gitattributes
          git add .
          git config user.email "bot@airkarta.com"
          git config user.name "Auto Sync"
          git commit -m "Auto sync to HF"
          git remote add space https://user:$HF_TOKEN@huggingface.co/spaces/$HF_SPACE
          git push --force space main:main
